version: '3'
services:

  nginx:
    restart: unless-stopped
    image:  nginx
    ports:
#    - 443:443
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./cert.pem:/etc/nginx/cert.pem
#      - ./privkey.pem:/etc/nginx/privkey.pem
      - ./htpasswd:/etc/nginx/.htpasswd

  webdav:
    restart: unless-stopped
    image:  ionelmc/webdav
    expose:
    - 8080
    volumes:
      - /home/vm_user/webdav-data:/media
