version: '3'
services:

  nginx:
    restart: unless-stopped
    image:  nginx
    ports:
    - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
      - ./htpasswd:/etc/nginx/.htpasswd

  webdav:
    restart: unless-stopped
    image:  bytemark/webdav
    environment:
      LOCATION: /webdav
    ports:
    - 80:80
    volumes:
      - webdav-data:/var/lib/dav


volumes:
  webdav-data:
